version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      NODE_ENV: production
      HOST: '0.0.0.0'
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.turbo
      - /app/apps/frontend/node_modules
      - ./apps/frontend/public:/app/apps/frontend/public